name: "Spelling Check"

on:
  - push
  - pull_request

jobs:
  check:
    # run on all push events or on PR syncs not from the same repo
    if: github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name

    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check for misspelt words
        uses: crate-ci/typos@v1.24.6